ELECTRONIC_CHOICES = [
    ('Kompyuter', 'Kompyuter'),
    ('Noutbuk', 'Noutbuk'),
    ('Planshet', 'Planshet'),
    ('Smartfon', 'Smartfon'),
    ('Televizor', 'Televizor'),
    ('Radioni Ko\'taruvchi', 'Radioni Ko\'taruvchi'),
    ('Fotoapparat', 'Fotoapparat'),
    ('Videokamera', 'Videokamera'),
    ('Printer', 'Printer'),
    ('Skaner', 'Skaner'),
    ('Kseroks', 'Kseroks'),
    ('Router', 'Router'),
    ('Modem', 'Modem'),
    ('Monitor', 'Monitor'),
    ('Klaviatura', 'Klaviatura'),
    ('Sichqoncha', 'Sichqoncha'),
    ('USB Fleshka', 'USB Fleshka'),
    ('Qattiq Disk', 'Qattiq Disk'),
    ('SSD Disk', 'SSD Disk'),
    ('Quvvatlantirgich', 'Quvvatlantirgich'),
    ('Quvvat Banki', 'Quvvat Banki'),
    ('Elektr Choynak', 'Elektr Choynak'),
    ('Mikrotolqinli Pech', 'Mikrotolqinli Pech'),
    ('Elektr Pech', 'Elektr Pech'),
    ('Konditsioner', 'Konditsioner'),
    ('Muzlatgich', 'Muzlatgich'),
    ('Kir Yuvish Mashinasi', 'Kir Yuvish Mashinasi'),
    ('Idish Yuvish Mashinasi', 'Idish Yuvish Mashinasi'),
    ('Chang Yutgich', 'Chang Yutgich'),
    ('Fen', 'Fen'),
    ('Elektr Cho\'tkasi', 'Elektr Cho\'tkasi'),
    ('Quloqchin', 'Quloqchin'),
    ('Mikrofon', 'Mikrofon'),
    ('Kichik Audio Tizim', 'Kichik Audio Tizim'),
    ('Speaker', 'Speaker'),
    ('Uy Teatri Tizimi', 'Uy Teatri Tizimi'),
    ('O\'yin Konsoli', 'O\'yin Konsoli'),
    ('Dj O\'yin Paneli', 'Dj O\'yin Paneli'),
    ('Proektor', 'Proektor'),
    ('Elektr Gitara', 'Elektr Gitara'),
    ('Elektr Pianino', 'Elektr Pianino'),
    ('Sintezator', 'Sintezator'),
    ('Elektr Baraban', 'Elektr Baraban'),
    ('Elektr Simsiz Qo\'lqop', 'Elektr Simsiz Qo\'lqop'),
    ('Elektr Burg\'ulash', 'Elektr Burg\'ulash'),
    ('Lazer Nuri', 'Lazer Nuri'),
    ('Elektr Payvandlash Uskunasi', 'Elektr Payvandlash Uskunasi'),
    ('Elektr Ko\'rikchi', 'Elektr Ko\'rikchi'),
    ('Elektr Suv Qizdirgich', 'Elektr Suv Qizdirgich'),
    ('Elektr Panjara', 'Elektr Panjara'),
    ('Elektr Pechka', 'Elektr Pechka'),
    ('Elektr Gilam', 'Elektr Gilam'),
    ('Elektr O\'choq', 'Elektr O\'choq'),
    ('Elektr Termometr', 'Elektr Termometr'),
    ('Elektr Dazmol', 'Elektr Dazmol'),
    ('Elektr Tartibga Soluvchi', 'Elektr Tartibga Soluvchi'),
    ('Elektr O\'tiradigan Joy', 'Elektr O\'tiradigan Joy'),
    ('Elektr Mexanizm', 'Elektr Mexanizm'),
    ('Elektr Aspirator', 'Elektr Aspirator'),
    ('Elektr Kichkina Ventilyator', 'Elektr Kichkina Ventilyator'),
    ('Elektr Kir Yuvish Mashinasi', 'Elektr Kir Yuvish Mashinasi'),
    ('Elektr Cho\'yan', 'Elektr Cho\'yan'),
    ('Elektr Qog\'oz Kesish Mashinasi', 'Elektr Qog\'oz Kesish Mashinasi'),
    ('Elektr Go\'sht Maydalash Mashinasi', 'Elektr Go\'sht Maydalash Mashinasi'),
    ('Elektr Soch Oluvchi Mashina', 'Elektr Soch Oluvchi Mashina'),
    ('Elektr Yuz Massaji', 'Elektr Yuz Massaji'),
    ('Elektr Bolg\'a', 'Elektr Bolg\'a'),
    ('Elektr Sirenasi', 'Elektr Sirenasi'),
    ('Elektr Eshik Qo\'ng\'irog\'i', 'Elektr Eshik Qo\'ng\'irog\'i'),
    ('Elektr Soat', 'Elektr Soat'),
    ('Elektr Budilnik', 'Elektr Budilnik'),
    ('Elektr Zarb Beruvchi Mashina', 'Elektr Zarb Beruvchi Mashina'),
    ('Elektr Matkap', 'Elektr Matkap'),
    ('Elektr Mo\'ri', 'Elektr Mo\'ri'),
    ('Elektr Sim Qotiruvchi', 'Elektr Sim Qotiruvchi'),
    ('Elektr Ip O\'rgich', 'Elektr Ip O\'rgich'),
    ('Elektr Tikuv Mashinasi', 'Elektr Tikuv Mashinasi'),
    ('Elektr O\'lchagich', 'Elektr O\'lchagich'),
    ('Elektr Avtomatika', 'Elektr Avtomatika'),
    ('Elektr Ish Stoli', 'Elektr Ish Stoli'),
    ('Elektr O\'roq', 'Elektr O\'roq'),
    ('Elektr To\'lov Moslamasi', 'Elektr To\'lov Moslamasi'),
    ('Elektr Ventilyator', 'Elektr Ventilyator'),
    ('Elektr Telefon', 'Elektr Telefon'),
    ('Elektr Avtomat', 'Elektr Avtomat'),
    ('Elektr Yuqori Bosim', 'Elektr Yuqori Bosim'),
    ('Elektr Magnit', 'Elektr Magnit'),
    ('Elektr Yuritma', 'Elektr Yuritma'),
    ('Elektr Tushunish Moslamasi', 'Elektr Tushunish Moslamasi'),
    ('Elektr Hisobotchi', 'Elektr Hisobotchi'),
    ('Elektr Navigatsiya Tizimi', 'Elektr Navigatsiya Tizimi'),
    ('Elektr Signalizatsiya Tizimi', 'Elektr Signalizatsiya Tizimi'),
    ('Elektr Radiatsiya O\'lchagich', 'Elektr Radiatsiya O\'lchagich'),
    ('Elektr Kameralari', 'Elektr Kameralari'),
    ('Elektr Nazorat Moslamasi', 'Elektr Nazorat Moslamasi'),
    ('Elektr To\'siq', 'Elektr To\'siq'),
    ('Elektr Yorug\'lik Moslamasi', 'Elektr Yorug\'lik Moslamasi'),
    ('Elektr Dush', 'Elektr Dush'),
    ('Elektr Qozon', 'Elektr Qozon'),
    ('Elektr Moy Qizdirgich', 'Elektr Moy Qizdirgich'),
]

daily_usage_hours = {
    'Kompyuter': 5,
    'Noutbuk': 6,
    'Planshet': 3,
    'Smartfon': 8,
    'Televizor': 4,
    'Radioni ko\'taruvchi': 2,
    'Fotoapparat': 0.5,
    'Videokamera': 0.5,
    'Printer': 0.3,
    'Skaner': 0.2,
    'Kseroks': 0.5,
    'Router': 24,
    'Modem': 24,
    'Monitor': 5,
    'Klaviatura': 5,
    'Sichqoncha': 5,
    'USB fleshka': 1,
    'Qattiq disk': 5,
    'SSD disk': 5,
    'Quvvatlantirgich': 2,
    'Quvvat banki': 2,
    'Elektr choynak': 0.5,
    'Mikrotolqinli pech': 0.5,
    'Elektr pech': 0.5,
    'Konditsioner': 8,
    'Muzlatgich': 24,
    'Kir yuvish mashinasi': 1,
    'Idish yuvish mashinasi': 1,
    'Chang yutgich': 0.5,
    'Fen': 0.5,
    'Elektr cho\'tkasi': 0.2,
    'Quloqchin': 2,
    'Mikrofon': 1,
    'Kichik audio tizim': 2,
    'Speaker': 2,
    'Uy teatri tizimi': 3,
    'O\'yin konsoli': 2,
    'Dj o\'yin paneli': 1,
    'Proektor': 1,
    'Elektr gitara': 1,
    'Elektr pianino': 1,
    'Sintezator': 1,
    'Elektr baraban': 1,
    'Elektr simsiz qo\'lqop': 0.5,
    'Elektr burg\'ulash': 1,
    'Lazer nuri': 1,
    'Elektr payvandlash uskunasi': 1,
    'Elektr ko\'rikchi': 0.5,
    'Elektr suv qizdirgich': 3,
    'Elektr panjara': 1,
    'Elektr pechka': 1,
    'Elektr gilam': 2,
    'Elektr o\'choq': 2,
    'Elektr termometr': 24,
    'Elektr dazmol': 0.5,
    'Elektr tartibga soluvchi': 2,
    'Elektr o\'tiradigan joy': 5,
    'Elektr mexanizm': 5,
    'Elektr aspirator': 0.5,
    'Elektr kichkina ventilyator': 3,
    'Elektr kir yuvish mashinasi': 1,
    'Elektr cho\'yan': 0.5,
    'Elektr qog\'oz kesish mashinasi': 0.5,
    'Elektr go\'sht maydalash mashinasi': 0.5,
    'Elektr soch oluvchi mashina': 0.5,
    'Elektr yuz massaji': 0.5,
    'Elektr bolg\'a': 1,
    'Elektr sirenasi': 24,
    'Elektr eshik qo\'ng\'irog\'i': 1,
    'Elektr soat': 24,
    'Elektr budilnik': 24,
    'Elektr zarb beruvchi mashina': 0.5,
    'Elektr matkap': 0.5,
    'Elektr mo\'ri': 1,
    'Elektr sim qotiruvchi': 0.5,
    'Elektr ip o\'rgich': 0.5,
    'Elektr tikuv mashinasi': 1,
    'Elektr o\'lchagich': 1,
    'Elektr avtomatika': 24,
    'Elektr ish stoli': 5,
    'Elektr o\'roq': 1,
    'Elektr to\'lov moslamasi': 1,
    'Elektr ventilyator': 8,
    'Elektr telefon': 8,
    'Elektr avtomat': 24,
    'Elektr yuqori bosim': 1,
    'Elektr magnit': 1,
    'Elektr yuritma': 1,
    'Elektr tushunish moslamasi': 1,
    'Elektr hisobotchi': 1,
    'Elektr navigatsiya tizimi': 1,
    'Elektr signalizatsiya tizimi': 24,
    'Elektr radiatsiya o\'lchagich': 1,
    'Elektr kameralari': 24,
    'Elektr nazorat moslamasi': 24,
    'Elektr to\'siq': 24,
    'Elektr yorug\'lik moslamasi': 6,
    'Elektr dush': 0.5,
    'Elektr qozon': 0.5,
    'Elektr moy qizdirgich': 0.5,
}
energy_consumption_per_hour = {
    'Kompyuter': 0.1,
    'Noutbuk': 0.05,
    'Planshet': 0.015,
    'Smartfon': 0.005,
    'Televizor': 0.1,
    'Radioni ko\'taruvchi': 0.02,
    'Fotoapparat': 0.01,
    'Videokamera': 0.015,
    'Printer': 0.05,
    'Skaner': 0.03,
    'Kseroks': 0.3,
    'Router': 0.01,
    'Modem': 0.01,
    'Monitor': 0.06,
    'Klaviatura': 0.001,
    'Sichqoncha': 0.001,
    'USB fleshka': 0.001,
    'Qattiq disk': 0.01,
    'SSD disk': 0.01,
    'Quvvatlantirgich': 0.01,
    'Quvvat banki': 0.01,
    'Elektr choynak': 1.5,
    'Mikrotolqinli pech': 1.2,
    'Elektr pech': 1.0,
    'Konditsioner': 2.0,
    'Muzlatgich': 0.15,
    'Kir yuvish mashinasi': 0.5,
    'Idish yuvish mashinasi': 1.2,
    'Chang yutgich': 0.5,
    'Fen': 1.5,
    'Elektr cho\'tkasi': 0.002,
    'Quloqchin': 0.002,
    'Mikrofon': 0.001,
    'Kichik audio tizim': 0.05,
    'Speaker': 0.05, 'Uy teatri tizimi': 0.3,
    'O\'yin konsoli': 0.15,
    'Dj o\'yin paneli': 0.1,
    'Proektor': 0.2,
    'Elektr gitara': 0.02,
    'Elektr pianino': 0.05,
    'Sintezator': 0.05,
    'Elektr baraban': 0.05,
    'Elektr simsiz qo\'lqop': 0.01,
    'Elektr burg\'ulash': 0.5,
    'Lazer nuri': 0.01,
    'Elektr payvandlash uskunasi': 2.0,
    'Elektr ko\'rikchi': 0.01,
    'Elektr suv qizdirgich': 1.5,
    'Elektr panjara': 1.0,
    'Elektr pechka': 1.5,
    'Elektr gilam': 0.1,
    'Elektr o\'choq': 1.5,
    'Elektr termometr': 0.001,
    'Elektr dazmol': 1.2,
    'Elektr tartibga soluvchi': 0.01,
    'Elektr o\'tiradigan joy': 0.1,
    'Elektr mexanizm': 0.1,
    'Elektr aspirator': 0.05,
    'Elektr kichkina ventilyator': 0.05,
    'Elektr kir yuvish mashinasi': 0.5,
    'Elektr cho\'yan': 1.0,
    'Elektr qog\'oz kesish mashinasi': 0.05,
    'Elektr go\'sht maydalash mashinasi': 0.5,
    'Elektr soch oluvchi mashina': 0.01,
    'Elektr yuz massaji': 0.01,
    'Elektr bolg\'a': 0.5,
    'Elektr sirenasi': 0.01,
    'Elektr eshik qo\'ng\'irog\'i': 0.001,
    'Elektr soat': 0.001,
    'Elektr budilnik': 0.001,
    'Elektr zarb beruvchi mashina': 0.5,
    'Elektr matkap': 0.5,
    'Elektr mo\'ri': 0.05,
    'Elektr sim qotiruvchi': 0.05,
    'Elektr ip o\'rgich': 0.05,
    'Elektr tikuv mashinasi': 0.05,
    'Elektr o\'lchagich': 0.01,
    'Elektr avtomatika': 0.01,
    'Elektr ish stoli': 0.1,
    'Elektr o\'roq': 0.5,
    'Elektr to\'lov moslamasi': 0.01,
    'Elektr ventilyator': 0.05,
    'Elektr telefon': 0.005,
    'Elektr avtomat': 0.01,
    'Elektr yuqori bosim': 0.5,
    'Elektr magnit': 0.05,
    'Elektr yuritma': 0.05,
    'Elektr tushunish moslamasi': 0.01,
    'Elektr hisobotchi': 0.01,
    'Elektr navigatsiya tizimi': 0.01,
    'Elektr signalizatsiya tizimi': 0.01,
    'Elektr radiatsiya o\'lchagich': 0.01,
    'Elektr kameralari': 0.01,
    'Elektr nazorat moslamasi': 0.01,
    'Elektr to\'siq': 0.01,
    'Elektr yorug\'lik moslamasi': 0.05,
    'Elektr dush': 1.5,
    'Elektr qozon': 1.5,
    'Elektr moy qizdirgich': 1.5,
}

REPORT_CHOICES = [
    ('Noqonuniy daraxt kesish', 'Noqonuniy daraxt kesish'),
    ('Noqonuniy musur tashlash', 'Noqonuniy musur tashlash'),
    ('Noqonuniy qurilish', 'Noqonuniy qurilish'),
    ('Atrof-muxitni ifloslantirish', 'Atrof-muxitni ifloslantirish'),
    ("Yovvoyi tabiatni noqonuniy ovlash", "Yovvoyi tabiatni noqonuniy ovlash"),
]
