# Generated by Django 4.2.14 on 2024-08-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='report',
            new_name='home',
        ),
    ]
